In [1]:
import numpy as np

In [2]:
# numpy array can be thought of a python list with added features
# can have multiple dimensions

In [3]:
x = np.array([0, 1, 2, 3])

In [4]:
x

array([0, 1, 2, 3])

In [5]:
# multiple dimension lists

In [6]:
w = np.array([[0, 1, 2, 3], [4, 5, 6, 7]])

In [7]:
w

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [15]:
# arange works similarly to python range function
# returns an array

# reshape returns an array containing the same data with a new shape

y = np.arange(25).reshape(5, 5)

In [16]:
y

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [18]:
# element wise functions return new array

np. square(x)    # square each value

array([0, 1, 4, 9], dtype=int32)

In [19]:
np.sqrt(x)       # square root of each value

array([ 0.        ,  1.        ,  1.41421356,  1.73205081])

In [20]:
np.cos(x)        # cosine of each value

array([ 1.        ,  0.54030231, -0.41614684, -0.9899925 ])

In [21]:
# aggregator functions return a single value based on array
# takes set of multiple data values and condenses/aggregates them

np.max(x)

3

In [22]:
np.min(x)

0

In [24]:
np.mean(x)

1.5

In [32]:
# other functions

In [31]:
x.itemsize

4

In [33]:
x.shape

(4,)